### ISSUE TITLE
Question about the fusing of embeddings

### ISSUE THREAD

**Issue by Ch3nYe** [OSUSecLab/SymLM#2]
Hi,

It's a great work. I have already read the paper, there is a question. In sec3, you metion that fusing $E^{in}$ to $E_\mathcal{I}$ , how to concatenate multiple $E^{in} \in \mathcal{R}^{(k+2)\times m}$ to a vector. Is it flatten multiple $E^{in}$ matrix and concatenate them head-tail? 

In addition, the fusing of  $E_\mathcal{I}$ and $E_\mathcal{C}$ has the same question. 

Expect to your reply.

**Comment by xinjin95** [comment]
Hi @Ch3nYe,

Thank you for your interest! Sorry for the late reply due to a submission deadline.

$E^{in}$, $E_{I}$, and $E_{C}$ are 3D tensors, i.e., with shape (N, M, K), where N is the batch size, K is the embedding size, M is the intermediate number. During the calculation, N and K are fixed (or user defined), M will be different for$E^{in}$, $E_{I}$, and $E_{C}$.

We perform the concatenation on the 2nd dimension. That is, given two tensors with shapes of $(N, M_1, K)$ and $(N, M_2, K)$, the concatenated tensor will be $(N, M_1+M_2, K)$. This concatenation rule is used for embedding fusion.

Hope this will answer your question.

Best,
Xin

**Comment by Ch3nYe** [comment]
I see, thanks. 👍
