### ISSUE TITLE
An fixed path

### ISSUE THREAD

**Issue by Ch3nYe** [OSUSecLab/SymLM#6]
in fairseq_cli/preprocess.py line 177
'/home/xin/Documents/project/binary-semantics/stateformer/result/effect_preprocessing/wo_vocab/binarization.txt'

this path is fixed and there is no explaination about it.
It blocks reproduce experiments.

**Comment by xinjin95** [comment]
Hi @Ch3nYe,

Thanks for reporting the bug! It has been fixed.

Let us know if there are any other problems.

**Comment by Ch3nYe** [comment]
Hi XinJin, 

I'm trying to deploy your method on a real world binary dataset, which is consist of unstripped binaries, but they have not dwarf debugging info. I see that your data preprocessing script [(prepare_dataset.py#L333)](https://github.com/OSUSecLab/SymLM/blob/main/dataset_generation/prepare_dataset.py#L333) extracts functions based on dwarf information.

Can I extract functions without the dwarf infomation for your model training? 

If that is neccessary for your preprocessing, May I have your binary dataset described in your CCS paper?

Looking forward your reply.

**Comment by Ch3nYe** [comment]
Hi XinJin,

Thanks for your fixing. 😊

I'm trying to deploy your method on a real world binary dataset, which is consist of unstripped binaries, but they have not dwarf debugging info. I see that your data preprocessing script [(prepare_dataset.py#L333)](https://github.com/OSUSecLab/SymLM/blob/main/dataset_generation/prepare_dataset.py#L333) extracts functions based on dwarf information.

Can I extract functions without the dwarf infomation for your model training?

If that is neccessary for your preprocessing, May I have your binary dataset described in your CCS paper?

Looking forward your reply.

**Comment by xinjin95** [comment]
> Can I extract functions without the dwarf information for your model training?

For my current preprocessing script, debug info is necessary because we used function names as key to retrieve data for callees can callers. Ideally, the debug info is not necessary as the data needed for testing purposes can be extracted from .text sections and callee/caller addresses can serve as keys. If the .text section isn't unstripped, we could obtain necessary data, i.e., `['static', 'inst_pos_emb', 'op_pos_emb', 'arch_emb', 'byte1', 'byte2', 'byte3', 'byte4']`. We're thinking about developing the scripts to obtain dataset without debug info. 

> If that is necessary for your preprocessing, may I have your binary dataset described in your CCS paper?

As for dataset, it's extremely large, e.g., ~100GB, which blocked us releasing the whole dataset to public. Are you working on binaries in specific compilation settings, e.g., X64-O0? If so, I can share some subsets in a proper way.

**Comment by Ch3nYe** [comment]
Hi JinXin

I see.

For now, `X64-O0` is ok for us. If you can share it, we will appraciate it.

Thanks.

**Comment by xinjin95** [comment]
Hi @Ch3nYe,

Please find the dataset via https://drive.google.com/drive/folders/13KWLv3KMjpYc9_IizPblppomDEF0dBBo?usp=sharing. Let us know if there are any problems with downloading the dataset.

**Comment by Ch3nYe** [comment]
Thanks.
